# Generated by Django 5.2.11 on 2026-02-10 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (Opcional)')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador URL (automático)')),
            ],
            options={
                'verbose_name': 'Área / Departamento',
                'verbose_name_plural': 'Áreas / Departamentos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Tipo de Documento (Ej. Nómina, Facturas)')),
                ('slug', models.SlugField(verbose_name='Identificador URL')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_documento', to='main.area', verbose_name='Pertenece al Área')),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'unique_together': {('area', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('archivo_pdf', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='main.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento PDF',
                'verbose_name_plural': 'Documentos PDF',
                'ordering': ['-fecha_publicacion', '-created_at'],
            },
        ),
    ]
